services:
  mariadb:
    image: mariadb:inception
    container_name: mariadb                 
    volumes:                                    # volume build in the container
      - mariadb:/var/lib/mysql
    networks:
      - inception                               # to which network it belongs
    build: requirements/mariadb                 # whereis the docker file
    env_file: .env                              # environnement file
    restart:  on-failure                        # restart until stop
    expose:
      - "3306"

  nginx:
    image: nginx:inception
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:                                 # do not start NGINX until WordPress has not start
      - wordpress
    build: requirements/nginx
    env_file: .env
    ports:
      - "443:443"                               # specify the port who will be expose on vm
    restart: on-failure                         # this containers will restart only if he crash


  wordpress:
    image: wordpress:inception
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: requirements/wordpress
    depends_on:                                 # WordPress will start only after MariaDB
      - mariadb
    restart: on-failure
    expose:
      - "9000"


volumes:
  wordpress:
    name: wordpress
    driver: local                               # store the volume on local
    driver_opts:
      type: 'none'                              # no type specified
      o:  'bind'                                # This option tells Docker that you want to use a 
                                                # bind mount, which is a specific type of mount where 
                                                # a directory on the host is bound directly 
                                                # into a container.

      device: '/home/tmaillar/data/wordpress'   # where to store the dir on local

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'          
      o:  'bind'                                # bind means that files are mounted directly from 
                                                # a directory on the host file system, and any changes 
                                                # made in that directory are reflected in real time 
                                                # inside the container, and vice versa.                    
      device: '/home/tmaillar/data/mariadb'

networks:
    inception:
      name: inception
      driver: bridge                            # bridge specify to docker to auto install rule
                                                # for the 3 container can communicate
